// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAciDujHq6GSmow-gQag2MJvnQK9la3wwU',
    appId: '1:611649025987:web:10e0fbab9d8c91a9292f76',
    messagingSenderId: '611649025987',
    projectId: 'fire-chat-9126a',
    authDomain: 'fire-chat-9126a.firebaseapp.com',
    storageBucket: 'fire-chat-9126a.firebasestorage.app',
    measurementId: 'G-7L9ZXF7QFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALvbW2cKdCxvkIOa21l3NSS8smvDiRb0Q',
    appId: '1:611649025987:android:8eea3d027b41494a292f76',
    messagingSenderId: '611649025987',
    projectId: 'fire-chat-9126a',
    storageBucket: 'fire-chat-9126a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfRz_X7GsMz5IOa9GdPIjlj-CIMyWiU3I',
    appId: '1:611649025987:ios:8aadeb458ae6da12292f76',
    messagingSenderId: '611649025987',
    projectId: 'fire-chat-9126a',
    storageBucket: 'fire-chat-9126a.firebasestorage.app',
    iosBundleId: 'com.example.fireChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfRz_X7GsMz5IOa9GdPIjlj-CIMyWiU3I',
    appId: '1:611649025987:ios:8aadeb458ae6da12292f76',
    messagingSenderId: '611649025987',
    projectId: 'fire-chat-9126a',
    storageBucket: 'fire-chat-9126a.firebasestorage.app',
    iosBundleId: 'com.example.fireChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAciDujHq6GSmow-gQag2MJvnQK9la3wwU',
    appId: '1:611649025987:web:9e7e0062c9fcd3d9292f76',
    messagingSenderId: '611649025987',
    projectId: 'fire-chat-9126a',
    authDomain: 'fire-chat-9126a.firebaseapp.com',
    storageBucket: 'fire-chat-9126a.firebasestorage.app',
    measurementId: 'G-WY6F0CQ5JM',
  );
}
